increase memory of anndata_manipulate
usegalaxy-eu/infrastructure-playbook pull request #1217
Opened 2024-05-28 16:44 UTC by pavanvidem

2024-05-28 16:52 UTC, sanjaysrikakulam commented
@pavanvidem Are you sure about this? Do we know how large the `input_size` can be?

2024-05-28 16:55 UTC, pavanvidem commented
Currently, the tools is failing to concatenate 2 anndata objects of 2GB each.

2024-05-28 16:56 UTC, pavanvidem commented
Is the default memory ~3.8G?

2024-05-28 16:58 UTC, sanjaysrikakulam commented
The default from TPV shared DB is `cores: 4`, and mem will be lazily evaluated from our TPV config to `mem: cores * 3.8`, so basically, we are assigning `~15 GB` of memory.

Now, by overwriting this, we might not cover all possible scenarios. We must cover a minimum and maximum and your case of `input_size * 4`.

2024-05-28 17:00 UTC, pavanvidem commented
Then `input_size * 4` is only a bit larger than default. I will write a case for larger files only.

2024-05-28 17:06 UTC, sanjaysrikakulam commented
Something like this might work `min(max(input_size*4, 3.8*cores), 128)`

2024-05-28 17:11 UTC, pavanvidem commented
all those tools need only 1 core

2024-05-28 17:22 UTC, sanjaysrikakulam requested changes

2024-05-28 17:22 UTC, sanjaysrikakulam commented on files/galaxy/tpv/tools.yml
> +  toolshed.g2.bx.psu.edu/repos/iuc/anndata_import/anndata_manipulate/.*:
```suggestion
  toolshed.g2.bx.psu.edu/repos/iuc/anndata_import/anndata_import/.*
```

2024-05-28 17:22 UTC, sanjaysrikakulam commented on files/galaxy/tpv/tools.yml
> +  toolshed.g2.bx.psu.edu/repos/iuc/anndata_export/anndata_manipulate/.*:
```suggestion
  toolshed.g2.bx.psu.edu/repos/iuc/anndata_export/anndata_export/.*:
```

2024-05-28 17:22 UTC, sanjaysrikakulam commented on files/galaxy/tpv/tools.yml
> +  toolshed.g2.bx.psu.edu/repos/iuc/anndata_inspect/anndata_manipulate/.*:
```suggestion
  toolshed.g2.bx.psu.edu/repos/iuc/anndata_inspect/anndata_inspect/.*:
```

2024-05-28 17:22 UTC, sanjaysrikakulam commented on files/galaxy/tpv/tools.yml
> +  toolshed.g2.bx.psu.edu/repos/iuc/modify_loom/anndata_manipulate/.*:
```suggestion
  toolshed.g2.bx.psu.edu/repos/iuc/modify_loom/modify_loom/.*:
```

2024-05-29 05:50 UTC, sanjaysrikakulam approved these changes

2024-05-29 05:50 UTC, merged