Update destinations.yml.j2
usegalaxy-eu/infrastructure-playbook pull request #912
Opened 2023-09-21 13:32 UTC by martindemko

Hi guys,
I'm trying to handle different alphafold database versions for CESNET clusters. Not exactly sure if this is the correct way to do it, still new with TPV. If I look to you as totally lost, please, advise me a little bit.
Thanks,
Martin

2023-09-21 15:20 UTC, kysrpex requested changes

2023-09-21 15:20 UTC, kysrpex commented on files/galaxy/tpv/destinations.yml.j2
> +          singularity_volumes: "$job_directory:ro,$tool_directory:ro,$job_directory/outputs:rw,$working_directory:rw,/cvmfs/data.galaxyproject.org:ro,/storage/praha5-elixir/home/galaxyeu:/home/galaxy
```suggestion
      - if: tool.id.startswith("toolshed.g2.bx.psu.edu/repos/galaxy-australia/alphafold2/alphafold") and helpers.tool_version_gte(tool, "2.1.2+galaxy0") and helpers.tool_version_lt(tool, "2.3")
        env:
          ALPHAFOLD_DB: "/storage/brno11-elixir/projects/alphafold/alphafold.db-2.2"
        params:
          singularity_volumes: "$job_directory:ro,$tool_directory:ro,$job_directory/outputs:rw,$working_directory:rw,/cvmfs/data.galaxyproject.org:ro,$SCRATCHDIR,/storage/praha5-elixir/home/galaxyeu:/home/galaxyeu,$ALPHAFOLD_DB:/data/2.2:ro"
```

2023-09-21 15:20 UTC, kysrpex commented on files/galaxy/tpv/destinations.yml.j2
> +
```suggestion
      - if: tool.id.startswith("toolshed.g2.bx.psu.edu/repos/galaxy-australia/alphafold2/alphafold") and helpers.tool_version_gte(tool, "2.3")
        params:
          singularity_volumes: "$job_directory:ro,$tool_directory:ro,$job_directory/outputs:rw,$working_directory:rw,/cvmfs/data.galaxyproject.org:ro,$SCRATCHDIR,/storage/praha5-elixir/home/galaxyeu:/home/galaxyeu,$ALPHAFOLD_DB:/data/2.3:ro"

```

2023-09-21 15:22 UTC, kysrpex commented
Is Singularity actually reading your environment variables?

I am asking because depending on your setup you may need [an approach similar to ours](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/8d3532faae4719733d626b89e441acccb63acedd/files/galaxy/tpv/tools.yml#L259).

2023-09-25 14:04 UTC, martindemko commented
Thanks for the hint, I didn't think about that. However, ALPHAFOLD_DB is used outside of singularity in our case only ALPHAFOLD_USE_GPU is used inside, so I used your solution for it.

2023-09-25 14:05 UTC, kysrpex approved these changes

2023-09-25 14:06 UTC, merged