bump roles jenkins, java
usegalaxy-eu/infrastructure-playbook pull request #999
Opened 2023-11-17 11:15 UTC by mira-miracoli

part of:
- https://github.com/usegalaxy-eu/issues/issues/492

2023-11-17 11:16 UTC, bgruening commented on requirements.yaml
> +    version: patch-1
Is that temporary?

2023-11-17 11:16 UTC, mira-miracoli commented on requirements.yaml
> +    version: patch-1
it is just fixed

2023-11-17 11:21 UTC, bgruening approved these changes

2023-11-17 11:33 UTC, sanjaysrikakulam approved these changes

2023-11-17 12:10 UTC, kysrpex requested changes
Also you included [d3f3e3d](https://github.com/usegalaxy-eu/infrastructure-playbook/pull/999/commits/d3f3e3d60aefabfd3971452d21d640f8312786a4) and [92b634b](https://github.com/usegalaxy-eu/infrastructure-playbook/pull/999/commits/92b634b2acdf4b6e65b4cb79cfd664912a42a685) from https://github.com/usegalaxy-eu/infrastructure-playbook/pull/998. I guess this was not meant to be the case.

2023-11-17 12:10 UTC, kysrpex commented on group_vars/build.yml
> +  - "{{ byobu if ansible_distribution_major_version < '9' | default(omit) }}"
```suggestion
  - "{{ 'byobu' if ansible_distribution_major_version < '9' else omit }}"
```

Same story as [here](https://github.com/usegalaxy-eu/infrastructure-playbook/pull/998#discussion_r1397117191).

2023-11-17 12:14 UTC, sanjaysrikakulam approved these changes

2023-11-20 13:23 UTC, kysrpex commented on group_vars/build.yml
> +  - "{{ byobu if ansible_distribution_major_version < '9' | default(omit) }}"
Not resolved :(

2023-11-20 13:47 UTC, kysrpex approved these changes

2023-11-20 13:48 UTC, merged